id: 42
user: eq19
span: span-23
title: eQuantum
baseurl: /feed
repository: GlobalZones/feed
action: GlobalZones/maps/actions/runs/15345767155
description: ₠Quantum Project

#debug:
#  dist: false
#  compress: true
#  shortcodes: true

lsi: false
incremental: true
highlighter: rouge
plugins_dir: _plugins

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

exclude:
  - LICENSE
  - vendor/
  - action.yml  
  - Dockerfile

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
  spin: [3, 2]
  pinned: [maps, feed, lexer, parser, syntax, grammar, rapidjson, ventoy, magisk, duckdb, ci, templates]
  organization: [Chetabahana, FeedMapping, GlobalZones, HybridModels, JunctionTerms, KernelPatterns, MappingSystem, NeuralSystem, ObjectModules, VirtualNetworks, WeakNegative, WeakPositive, ZeroWeak]
